name: Build And Push Docker
on:
  repository_dispatch:
    types: [build_docker_el8_release_to_github]
  push:
    branches: [ el8-release-to-github ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build/Publish to Registry
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: yoannguion/rpmbuilder
        tags: el8-release-to-github
